permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Cleber Dantas
url: https://getfaster.io
enforce_ssl: getfaster.io
description: WebDev, WebPerf, Internet, Consulting, Talks, Training, Blog
title: Web, Etc e Tal
twitter: cleberdantas
email: cleberwd@mail.com
setAccountGA: UA-3470042-3
