markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Cleber Dantas
url: http://www.cleberdantas.com
description: WebDev, WebPerf, Internet, Consulting, Talks, Training, Blog
twitter: cleberdantas
title: Web, Etc e Tal
email: cleberwd@mail.com
setAccountGA: UA-3470042-3
