FORMAT: 1A
HOST: https://api.dietaesaude.com.br

# API Dieta e Saúde
Documentação da API do Dieta e Saúde

# GET /profissionais/{id}
+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Note to perform action with. Has example value.
+ Request (application/json)
    + Headers
        teste: bla
        oi: q
+ Response 200 (application/json)
    + Body
        {
          "Id": 2, "Nome": "Roberta Stella"
        }
    + Headers
        Oeeeeee: Muleke